[loggers]
keys=root,getVissim,importVolume

[handlers]
keys=consoleHandler

[formatters]
keys=screenFomatter


[logger_root]
level=DEBUG
handlers=consoleHandler

[logger_getVissim]
level=DEBUG
handlers=consoleHandler
qualname=getVissim
propagate = 0

[logger_importVolume]
level=DEBUG
handlers=consoleHandler
qualname=importVolume
propagate = 0


[handler_consoleHandler]
class=logging.StreamHandler
level=DEBUG
formatter=screenFomatter
args=(sys.stdout,)


[formatter_screenFomatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s